# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1t0hbFnqUdfqE1jz-D1Sym6sis4rnHB8D
"""

import matplotlib.pyplot as plt
import matplotlib.patches as patches

def hitung_dan_visualisasi_lengkap(lebar_kertas, tinggi_kertas, lebar_potongan, tinggi_potongan):
    best_total = 0
    best_layout = {}
    orientasi_item = [(lebar_potongan, tinggi_potongan), (tinggi_potongan, lebar_potongan)]

    # 1. POLA GRID MURNI
    for iw, ih in orientasi_item:
        kolom = int(lebar_kertas // iw)
        baris = int(tinggi_kertas // ih)
        if kolom * baris > best_total:
            best_total = kolom * baris
            best_layout = {
                "pola": "Grid Murni", "h1": tinggi_kertas, "h2": 0, "w_split": lebar_kertas,
                "b1_kiri_orient": (iw, ih), "b1_kiri_k": kolom, "b1_kiri_b": baris,
                "b1_kanan_orient": (iw, ih), "b1_kanan_k": 0, "b1_kanan_b": 0,
                "b2_orient": (iw, ih), "b2_k": 0, "b2_b": 0,
                "arah_potong_pertama": "horizontal", "posisi_potong": tinggi_kertas
            }

    # 2. POLA HYBRID 2 BLOK (Logika Sketsa)
    for h1 in range(0, int(tinggi_kertas) + 1):
        h2 = tinggi_kertas - h1
        for w_split in range(0, int(lebar_kertas) + 1):
            w_kiri = w_split
            w_kanan = lebar_kertas - w_split

            for iw_ak, ih_ak in orientasi_item:
                k_ak, b_ak = int(w_kiri // iw_ak), int(h1 // ih_ak)

                for iw_ap, ih_ap in orientasi_item:
                    k_ap, b_ap = int(w_kanan // iw_ap), int(h1 // ih_ap)

                    for iw_b, ih_b in orientasi_item:
                        k_b, b_b = int(lebar_kertas // iw_b), int(h2 // ih_b)

                        total = (k_ak * b_ak) + (k_ap * b_ap) + (k_b * b_b)
                        if total > best_total:
                            best_total = total
                            best_layout = {
                                "pola": "Hybrid Kombinasi", "h1": h1, "h2": h2, "w_split": w_split,
                                "b1_kiri_orient": (iw_ak, ih_ak), "b1_kiri_k": k_ak, "b1_kiri_b": b_ak,
                                "b1_kanan_orient": (iw_ap, ih_ap), "b1_kanan_k": k_ap, "b1_kanan_b": b_ap,
                                "b2_orient": (iw_b, ih_b), "b2_k": k_b, "b2_b": b_b,
                                "arah_potong_pertama": "horizontal", "posisi_potong": h2
                            }

    # --- PROSES GAMBAR VISUALISASI ---
    fig, ax = plt.subplots(figsize=(11, 11))
    ax.set_xlim(-10, lebar_kertas + 15)
    ax.set_ylim(-10, tinggi_kertas + 15)

    # Gambar Kertas Induk
    kertas_induk = patches.Rectangle((0, 0), lebar_kertas, tinggi_kertas, linewidth=2, edgecolor='black', facecolor='#f8f9fa')
    ax.add_patch(kertas_induk)

    # Label Dimensi Total Kertas Induk di bagian Luar
    ax.text(lebar_kertas / 2, tinggi_kertas + 3, f"{lebar_kertas} cm", color='black', fontsize=12, weight='bold', ha='center')
    ax.text(-4, tinggi_kertas / 2, f"{tinggi_kertas} cm", color='black', fontsize=12, weight='bold', va='center', rotation=90)

    no_potongan = 1

    def gambar_blok_dengan_dimensi(x_start, y_start, kolom, baris, iw, ih, warna):
        nonlocal no_potongan
        for b in range(baris):
            for k in range(kolom):
                x = x_start + (k * iw)
                y = y_start + (b * ih)

                # Gambar kotak potongan
                rect = patches.Rectangle((x, y), iw, ih, linewidth=1, edgecolor='#4a90e2', facecolor=warna, alpha=0.6)
                ax.add_patch(rect)

                # Tulis nomor potongan di tengah
                ax.text(x + iw/2, y + ih/2, f"{no_potongan}", color='black', weight='bold', fontsize=12, ha='center', va='center')

                # Tulis angka cm di setiap sisi bagian (Hanya untuk baris/kolom tepi agar tidak terlalu menumpuk teksnya)
                if b == 0: # Sisi bawah kotak
                    ax.text(x + iw/2, y + 1, f"{iw}", color='#333333', fontsize=8, ha='center')
                if b == baris - 1: # Sisi atas kotak
                    ax.text(x + iw/2, y + ih - 2, f"{iw}", color='#333333', fontsize=8, ha='center')
                if k == 0: # Sisi kiri kotak
                    ax.text(x + 1, y + ih/2, f"{ih}", color='#333333', fontsize=8, va='center', rotation=90)
                if k == kolom - 1: # Sisi kanan kotak
                    ax.text(x + iw - 2, y + ih/2, f"{ih}", color='#333333', fontsize=8, va='center', rotation=90)

                no_potongan += 1

    # Gambar komponen blok
    gambar_blok_dengan_dimensi(0, best_layout["h2"], best_layout["b1_kiri_k"], best_layout["b1_kiri_b"], best_layout["b1_kiri_orient"][0], best_layout["b1_kiri_orient"][1], '#a2d2ff')
    gambar_blok_dengan_dimensi(best_layout["w_split"], best_layout["h2"], best_layout["b1_kanan_k"], best_layout["b1_kanan_b"], best_layout["b1_kanan_orient"][0], best_layout["b1_kanan_orient"][1], '#bde0fe')
    gambar_blok_dengan_dimensi(0, 0, best_layout["b2_k"], best_layout["b2_b"], best_layout["b2_orient"][0], best_layout["b2_orient"][1], '#ffafcc')

    # --- GAMBAR GARIS POTONGAN PERTAMA ---
    if best_layout["h2"] > 0 and best_layout["h2"] < tinggi_kertas:
        posisi = best_layout["posisi_potong"]
        ax.axhline(y=posisi, color='red', linestyle='--', linewidth=3, label='Potongan Utama')
        ax.text(lebar_kertas + 2, posisi, f"POTONG PERTAMA\n(Y = {posisi} cm)", color='red', weight='bold', va='center', fontsize=10)

    # Indikator Tinggi sub-blok di bagian luar (membantu verifikasi potongan)
    if best_layout["h2"] > 0:
        ax.text(-2, best_layout["h2"] / 2, f"{best_layout['h2']} cm", color='blue', fontsize=10, va='center', rotation=90)
        ax.text(-2, best_layout["h2"] + (best_layout["h1"] / 2), f"{best_layout['h1']} cm", color='blue', fontsize=10, va='center', rotation=90)

    # Pengaturan Teks & Grafik
    plt.title(f"Rencana Potong Kertas ({best_layout['pola']})\nTotal Dapat: {best_total} Potongan", fontsize=14, weight='bold', pad=20)
    plt.legend(loc='upper right')
    plt.gca().set_aspect('equal', adjustable='box')
    plt.axis('off') # Mematikan penanda koordinat bawaan matplotlib agar tidak pusing melihat banyak angka
    plt.show()

    return best_total

# RUN DI GOOGLE COLAB
hitung_dan_visualisasi_lengkap(
    lebar_kertas=90,
    tinggi_kertas=120, # Parameter diubah ke penamaan fungsional variabel atas
    lebar_potongan=21.5,
    tinggi_potongan=33
)